exclude:
  - ignore

paths:
  - "tests/files/"

command:
  - regex: "a$"
    cmd: powershell -Command "cat {file_dir}/{file} > {file_dir}/b"

  - regex: "files/d$"
    chain: 
      - powershell -Command "cat {file_dir}/{file} >> {file_dir}/b"
      - powershell -Command "cat {file_dir}/b > {file_dir}/c"
